name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - production  # Only run this workflow for the 'production' branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your node version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build  # Customize based on your project's build command

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live  # Deploys to the 'live' channel, which is production by default
        projectId: your-firebase-project-id